language: elixir
elixir:
  - 1.1.1
  - 1.2.5
  - 1.3.2
otp_release:
  - 18.3
env:
  global:
    - MIX_ENV=test
before_install:
  - git submodule update --init --recursive
script:
  - "yes | mix do deps.get, deps.compile, compile --warnings-as-errors, coveralls.travis"
notifications:
  email:
    - jonas.schmidt@gmx.com
