language: elixir
elixir:
  - 1.2.6
  - 1.3.4
otp_release:
  - 18.3
  - 19.2
matrix:
  exclude:
    - elixir: 1.2.6
      otp_release: 19.2
env:
  global:
    - MIX_ENV=test
before_install:
  - git submodule update --init --recursive
script:
  - "yes | mix do deps.get, deps.compile, compile --warnings-as-errors, coveralls.travis"
notifications:
  email:
    - jonas.schmidt@gmx.com
