language: elixir
sudo: false
elixir:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
otp_release:
  - 19.3
  - 20.3
  - 21.0
matrix:
  exclude:
    - elixir: 1.5
      otp_release: 21.0
    - elixir: 1.8
      otp_release: 19.3
  include:
    - elixir: 1.8
      otp_release: 21.0
      env: DIALZYER_TASK="dialyzer --halt-exit-status,"
env:
  global:
    - MIX_ENV=test
before_install:
  - git submodule update --init --recursive
script:
  - "mix do deps.get, deps.compile, compile --warnings-as-errors, $DIALZYER_TASK coveralls.travis"
notifications:
  email:
    - jonas.schmidt@gmx.com
